### ISSUE TITLE
toFullwidthKana convert halfWidthKana(which has TENTEN) into 2 characters

### ISSUE THREAD

**Issue by hiep294** [yomotsu/japanese-string-utils#2]
The function toFullwidthKana convert halfWidthKana(which has TENTEN) into 2 characters, one is the character, two is the TENTEN
for example:
ｶﾞ => カ゛, can see that  カ゛has two characters: カ and ゛.
My expectation is that there is only one character which combine カ and ゛
Thank you!
https://codesandbox.io/s/tofullwidthkana-stis8?file=/src/App.js

**Comment by yomotsu** [comment]
Thanks for your report. The demo is very helpful👍
I'll fix that.

**Comment by yomotsu** [comment]
btw, there is a workaround.
```
toNFC( toFullwidthKana( "ｶﾞ" ) ); // ガ
```

**Comment by yomotsu** [comment]
This should be solved with v0.2.3 https://github.com/yomotsu/japanese-string-utils/commit/c5de54e15ccace27573c286f6f986bb22bfe7444
